### ISSUE TITLE
[1.10.2] Stuck in a bed in SinglePlayer, clicking leave bed produces no button to kick ones self

### ISSUE THREAD

**Issue by Morpheus1101** [gr8pefish/BedBugBuster#3] opened 2017-03-24 08:51 UTC
I have this mod installed an a few times ive been stuck in bed after sleeping and clicked the leave bed button, the button to kick myself dosent appear.

**Comment by gr8pefish** [comment] 2017-03-24 14:41
Hmm, well then I have a couple of clarifying questions for you:
* Does it _always_ not appear, or only sometimes? 
* Can you replicate it? 
* Has this been going on as far as you can tell or only recently?
* 1.10 or 1.11? Or both?

Thanks

**Comment by Morpheus1101** [comment] 2017-03-24 21:13
Yes, the fwe times now ive been stuck in bed, the kick button ha snot appeared for me, replicating i guess if i continually made it night an slept i possibly could and its been occuring since i added bed bugs to the pack im playing and 1.10 as i dont have any packs on 1.11 currently im playing

**Comment by Morpheus1101** [comment] 2017-03-25 07:47
Whilst streaming today it occured again, i was about 1hr 15min in when it occured, here is a screenshot you could say of it being morning and still in bed...

![2017-03-25_17 42 06](https://cloud.githubusercontent.com/assets/10524952/24320553/1599d472-1183-11e7-9795-c4e166e7fe7b.png)

**Comment by Morpheus1101** [comment] 2017-03-25 10:28
This is multiplayer, also occured on stream around 3hrs 56, with no button showing and having to use console to kick myself.  

BedBugs 1.10.2-1.1.5
Forge 12.18.3.2254

![2017-03-25_20 22 33](https://cloud.githubusercontent.com/assets/10524952/24321468/427ca6f2-1199-11e7-8ad3-57a58f08d101.png)

**Comment by ghost** [comment] 2017-03-26 04:45
I've got a similar issue in my pack atm, I haven't had time to trace the incompatibility causing it but the button doesn't appear at all.

**Comment by Morpheus1101** [comment] 2017-03-26 07:09
https://minecraft.curseforge.com/projects/ardentcraft-invictus/relations/dependencies

**Comment by Morpheus1101** [comment] 2017-04-07 23:09
This occurs in Multiplayer, but i have no more information i can possibly provide since its not something that can easily be reproduced consistently.

BB v1.1.6
Forge 12.18.3.2254

**Comment by gr8pefish** [comment] 2017-07-26 06:44
I can't reproduce, but there is a command to mitigate when things like this occur. Closing the issue, but if other people have it feel free to comment and I'll reopen/reinvestigate.

**Closed as completed by gr8pefish** 2017-07-26 06:44 UTC
Labels: bug, need more info
